name: Action to deploy Spring Boot app to Kubernetes
on:
  push:
    branches: [ master ]

jobs:
    build:
        name: Build and push Docker image to repository
        runs-on: ubuntu-latest
        steps:
            - name: Run docker build
              run: |
                  docker build -t noumbissi16/devops-journey:k8s-spring-0.0.1 ./k8s-spring-boot/demo
            - name: Push Docker image to repository
              run: |
                  docker push noumbissi16/devops-journey:k8s-spring-0.0.1